### ISSUE TITLE
k3ai init does nothing ( ERROR: unknown flag: --update-default-kubeconfig)

### ISSUE THREAD

**Issue by alexcpn** [kf5i/k3ai#34]
**Describe the bug**
k3ai inti does not work 

**To Reproduce**
Version : k3ai-core_0.2.3_linux_amd64.tar.gz

config file

```
cat kai-k3d.yaml 
kind: cluster
targetCustomizations:
- name: localK3d #name of the cluster instance not the name of the cluster
  enabled: true
  type: k3d
  config:  #default location of config file or your existing config file to copy
  clusterName: demo-win-k3d #name of the cluster (this need to be the same as in a config file)
  clusterDeployment: local
  clusterStart: "k3d create cluster" # in the default it was given k3d cluster create - which is wrong 
  spec:
  # If the OS is not needed may be removed so the three below are mutually exclusive, if not needed set them to null or remove it
    linux: "https://kind.sigs.k8s.io/dl/v0.9.0/kind-linux-amd64"
    # Everything from this repo will be ran in this cluster. You trust me right?
  plugins: 
  - repo: 
    name: jupyter-minimal
  - repo: 
    name: 
```
Trigger Init

```
k3ai init --config ./kai-k3d.yaml 
```
Ouput 
```
☑️	Checking requirements for local deployment...
☑️	Installing infrastructure for local deployment...
	Selected deployment type: k3d
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    97  100    97    0     0    374      0 --:--:-- --:--:-- --:--:--   374
100   624  100   624    0     0   1579      0 --:--:-- --:--:-- --:--:--  1579
100 7247k  100 7247k    0     0  6697k      0  0:00:01  0:00:01 --:--:-- 14.2M
ERROR: unknown flag: --update-default-kubeconfig
exit status 1
☑️	Infrastructure ready, proceeding to plugins installation (if any)...
☑️	Add Plugins to local deployment...
Plugin YAML content: [{https://raw.githubusercontent.com/kf5i/k3ai-plugins/main/common/jupyter/base/deployment.yaml file}], name: jupyter-minimal 
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
2021/08/10 10:26:22 Error during create: exit status 1
☑️	Plugins added to local deployment...
🎉	Local deployment completed, have fun with k3ai!
```
No cluster is created

```
kubectl config get-contexts
CURRENT   NAME   CLUSTER   AUTHINFO   NAMESPACE
```

**Expected behavior**

Cluster is created

**Additional context**

 Normal cluster creation is working directly using k3d

```
alexpunnen@pop-os:~$ k3d create cluster 
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.19.1) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Thanks for using kind! 😊
alexpunnen@pop-os:~$ kubectl config get-contexts
CURRENT   NAME        CLUSTER     AUTHINFO    NAMESPACE
*         kind-kind   kind-kind   kind-kind 
```
